editor_objects = {}
editor_currobjlist = {}
editor_objlist_reference = {}

function clearobjlist()
	editor_objects = {}
	editor_currobjlist = {}
	
	objlistdata.tags = {}
	objlistdata.tags_currobjlist = {}
	objlistdata.objectreference = {}
	objlistdata.tilereference = {}
	objlistdata.gridreference_overlap = {}
	objlistdata.gridreference_full = {}
	objlistdata.search = ""
	editor2.strings[SEARCHSTRING] = ""
	
	setundo_editor()
end

function formatobjlist()
	for i,v in ipairs(editor_objlist) do
		editor_objlist_reference[v.name] = i
	end
end

editor_objlist_order = {"algae","text_algae","baba","text_baba","bat","text_bat","belt","text_belt","bird","text_bird","bog","text_bog","bolt","text_bolt","box","text_box","brick","text_brick","bubble","text_bubble","bug","text_bug","cake","text_cake","cash","text_cash","circle","text_circle","cliff","text_cliff","cloud","text_cloud","cog","text_cog","crab","text_crab","crystal","text_crystal","cup","text_cup","cursor","door","text_door","dot","text_dot","dust","text_dust","eye","text_eye","fence","text_fence","fire","text_fire","flag","text_flag","flower","text_flower","foliage","text_foliage","foot","text_foot","fruit","text_fruit","fungi","text_fungi","fungus","text_fungus","ghost","text_ghost","grass","text_grass","hand","text_hand","hedge","text_hedge","husk","text_husk","ice","text_ice","jelly","text_jelly","keke","text_keke","key","text_key","ladder","text_ladder","lava","text_lava","leaf","text_leaf","line","text_line","love","text_love","me","text_me","moon","text_moon","orb","text_orb","pillar","text_pillar","pipe","text_pipe","reed","text_reed","robot","text_robot","rocket","text_rocket","rock","text_rock","rose","text_rose","rubble","text_rubble","shirt","text_shirt","sign","text_sign","skull","text_skull","spike","text_spike","square","text_square","star","text_star","statue","text_statue","stump","text_stump","sun","text_sun","tile","text_tile","tree","text_tree","triangle","text_triangle","ufo","text_ufo","wall","text_wall","water","text_water","worm","text_worm","text_right","text_up","text_left","text_down","text_all","text_and","text_best","text_red","text_blue","text_green","text_yellow","text_purple","text_pink","text_grey","text_black","text_white","text_brown","text_orange","text_bonus","text_broken","text_chill","text_cursor","text_defeat","text_eat","text_empty","text_end","text_done","text_facing","text_back","text_fall","text_fallright","text_fallup","text_fallleft","text_nudgedown","text_nudgeright","text_nudgeup","text_nudgeleft","text_turn","text_deturn","text_fear","text_float","text_follow","text_group","text_has","text_hide","text_hot","text_idle","text_is","text_level","text_lonely","text_often","text_seldom","text_make","text_melt","text_mimic","text_more","text_move","text_near","text_not","text_on","text_open","text_play","text_powered","text_power","text_pull","text_push","text_sad","text_safe","text_shift","text_shut","text_sink","text_sleep","text_still","text_stop","text_swap","text_tele","text_text","text_weak","text_win","text_without","text_wonder","text_word","text_you2","text_you","tinyhusk","tinytree","text_a","text_b","text_c","text_d","text_e","text_f","text_g","text_h","text_i","text_j","text_k","text_l","text_m","text_n","text_o","text_p","text_q","text_r","text_s","text_t","text_u","text_v","text_w","text_x","text_y","text_z",}

editor_objlist = {
	[1] = {
		name = "algae",
		unittype = "object",
		tags = {"water","plant","decorative"},
		tiling = -1,
		type = 0,
		layer = 15,
		colour = {5, 2},
	},
	[2] = {
		name = "text_algae",
		unittype = "text",
		tags = {"text","water","plant","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 0},
		colour_active = {5, 1},
	},
	[3] = {
		name = "baba",
		unittype = "object",
		tags = {"animal","common"},
		tiling = 2,
		type = 0,
		layer = 18,
		colour = {0, 3},
	},
	[4] = {
		name = "text_baba",
		unittype = "text",
		tags = {"text","animal","common"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
	},
	[5] = {
		name = "bat",
		unittype = "object",
		tags = {"cave","animal"},
		tiling = 4,
		type = 0,
		layer = 14,
		colour = {3, 1},
	},
	[6] = {
		name = "text_bat",
		unittype = "text",
		tags = {"text","cave","animal"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 0},
		colour_active = {3, 1},
	},
	[7] = {
		name = "belt",
		unittype = "object",
		tags = {"common","machine","movement"},
		tiling = 3,
		type = 0,
		layer = 11,
		colour = {1, 1},
	},
	[8] = {
		name = "text_belt",
		unittype = "text",
		tags = {"text","common","machine","movement"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 3},
	},
	[9] = {
		name = "bird",
		unittype = "object",
		tags = {"mountain","animal","sky"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {2, 3},
	},
	[10] = {
		name = "text_bird",
		unittype = "text",
		tags = {"text","mountain","animal","sky"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 2},
		colour_active = {2, 3},
	},
	[11] = {
		name = "text_w",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[12] = {
		name = "bog",
		sprite = "water",
		unittype = "object",
		tags = {"obstacle","forest"},
		tiling = 1,
		type = 0,
		layer = 2,
		colour = {5, 1},
	},
	[13] = {
		name = "text_bog",
		unittype = "text",
		tags = {"text","obstacle","forest"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[14] = {
		name = "bolt",
		unittype = "object",
		tags = {"machine","sky","danger"},
		tiling = 0,
		type = 0,
		layer = 16,
		colour = {2, 4},
	},
	[15] = {
		name = "text_bolt",
		unittype = "text",
		tags = {"text","machine","sky","danger"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 3},
		colour_active = {2, 4},
	},
	[16] = {
		name = "box",
		unittype = "object",
		tags = {"common","machine","item"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {6, 2},
	},
	[17] = {
		name = "text_box",
		unittype = "text",
		tags = {"text","common","machine","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 1},
	},
	[18] = {
		name = "brick",
		unittype = "object",
		tags = {"ruins","floor","decorative"},
		tiling = 1,
		type = 0,
		layer = 10,
		colour = {6, 3},
	},
	[19] = {
		name = "text_brick",
		unittype = "text",
		tags = {"text","ruins","floor","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 1},
	},
	[20] = {
		name = "bubble",
		unittype = "object",
		tags = {"water","decorative"},
		tiling = 4,
		type = 0,
		layer = 12,
		colour = {1, 4},
	},
	[21] = {
		name = "text_bubble",
		unittype = "text",
		tags = {"text","water","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[22] = {
		name = "bug",
		unittype = "object",
		tags = {"forest","animal"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {6, 2},
	},
	[23] = {
		name = "text_bug",
		unittype = "text",
		tags = {"text","forest","animal"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 2},
	},
	[24] = {
		name = "cake",
		unittype = "object",
		tags = {"item","decorative"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {4, 2},
	},
	[25] = {
		name = "text_cake",
		unittype = "text",
		tags = {"text","item","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 1},
		colour_active = {4, 2},
	},
	[26] = {
		name = "cash",
		unittype = "object",
		tags = {"item","danger","decorative"},
		tiling = -1,
		type = 0,
		layer = 12,
		colour = {5, 2},
	},
	[27] = {
		name = "text_cash",
		unittype = "text",
		tags = {"text","item","danger","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[28] = {
		name = "cliff",
		unittype = "object",
		tags = {"cave","obstacle"},
		tiling = 1,
		type = 0,
		layer = 14,
		colour = {6, 1},
	},
	[29] = {
		name = "text_cliff",
		unittype = "text",
		tags = {"text","cave","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 2},
	},
	[30] = {
		name = "cloud",
		unittype = "object",
		tags = {"sky","obstacle"},
		tiling = 1,
		type = 0,
		layer = 14,
		colour = {1, 4},
	},
	[31] = {
		name = "text_cloud",
		unittype = "text",
		tags = {"text","sky","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[32] = {
		name = "cog",
		unittype = "object",
		tags = {"machine","item","decorative"},
		tiling = 4,
		type = 0,
		layer = 16,
		colour = {0, 1},
	},
	[33] = {
		name = "text_cog",
		unittype = "text",
		tags = {"text","machine","item","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 2},
	},
	[34] = {
		name = "crab",
		unittype = "object",
		tags = {"water","animal"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {2, 2},
	},
	[35] = {
		name = "text_crab",
		unittype = "text",
		tags = {"text","water","animal"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[36] = {
		name = "cup",
		unittype = "object",
		tags = {"item","decorative"},
		tiling = -1,
		type = 0,
		layer = 13,
		colour = {1, 3},
	},
	[37] = {
		name = "text_cup",
		unittype = "text",
		tags = {"text","item","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 3},
	},
	[38] = {
		name = "cursor",
		unittype = "object",
		special = true,
		tags = {"special"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 2},
	},
	[39] = {
		name = "door",
		unittype = "object",
		tags = {"common","obstacle"},
		tiling = -1,
		type = 0,
		layer = 15,
		colour = {2, 2},
	},
	[40] = {
		name = "text_door",
		unittype = "text",
		tags = {"text","common","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[41] = {
		name = "dot",
		unittype = "object",
		tags = {"abstract","decorative"},
		tiling = -1,
		type = 0,
		layer = 12,
		colour = {0, 3},
	},
	[42] = {
		name = "text_dot",
		unittype = "text",
		tags = {"text","abstract","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[43] = {
		name = "dust",
		unittype = "object",
		tags = {"sky","decorative"},
		tiling = -1,
		type = 0,
		layer = 12,
		colour = {6, 2},
	},
	[44] = {
		name = "text_dust",
		unittype = "text",
		tags = {"text","sky","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 2},
		colour_active = {2, 4},
	},
	[45] = {
		name = "fence",
		unittype = "object",
		tags = {"autumn","obstacle"},
		tiling = 1,
		type = 0,
		layer = 14,
		colour = {6, 1},
	},
	[46] = {
		name = "text_fence",
		unittype = "text",
		tags = {"text","autumn","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 1},
	},
	[47] = {
		name = "fire",
		unittype = "object",
		tags = {"cave","decorative","danger"},
		tiling = -1,
		type = 0,
		layer = 15,
		colour = {2, 3},
	},
	[48] = {
		name = "text_fire",
		unittype = "text",
		tags = {"text","cave","decorative","danger"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 0},
		colour_active = {2, 2},
	},
	[49] = {
		name = "flag",
		unittype = "object",
		tags = {"common","item"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {2, 4},
	},
	[50] = {
		name = "text_flag",
		unittype = "text",
		tags = {"text","common","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[51] = {
		name = "flower",
		unittype = "object",
		tags = {"plant","forest","decorative"},
		tiling = -1,
		type = 0,
		layer = 12,
		colour = {3, 3},
	},
	[52] = {
		name = "text_flower",
		unittype = "text",
		tags = {"text","plant","forest","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 2},
		colour_active = {3, 3},
	},
	[53] = {
		name = "foliage",
		unittype = "object",
		tags = {"autumn","plant","decorative","floor"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {6, 0},
	},
	[54] = {
		name = "text_foliage",
		unittype = "text",
		tags = {"text","autumn","plant","decorative","floor"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 2},
		colour_active = {2, 3},
	},
	[55] = {
		name = "fruit",
		unittype = "object",
		tags = {"plant","forest","decorative"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {2, 2},
	},
	[56] = {
		name = "text_fruit",
		unittype = "text",
		tags = {"text","plant","forest","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[57] = {
		name = "fungi",
		unittype = "object",
		tags = {"plant","autumn","decorative"},
		tiling = -1,
		type = 0,
		layer = 8,
		colour = {6, 1},
	},
	[58] = {
		name = "text_fungi",
		unittype = "text",
		tags = {"text","plant","autumn","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 2},
	},
	[59] = {
		name = "fungus",
		unittype = "object",
		tags = {"plant","autumn","item","decorative"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {6, 1},
	},
	[60] = {
		name = "text_fungus",
		unittype = "text",
		tags = {"text","plant","autumn","item","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 1},
	},
	[61] = {
		name = "ghost",
		unittype = "object",
		tags = {"autumn","animal"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {4, 2},
	},
	[62] = {
		name = "text_ghost",
		unittype = "text",
		tags = {"text","autumn","animal"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 1},
		colour_active = {4, 2},
	},
	[63] = {
		name = "grass",
		unittype = "object",
		tags = {"plant","forest","floor"},
		tiling = 1,
		type = 0,
		layer = 10,
		colour = {5, 0},
	},
	[64] = {
		name = "text_grass",
		unittype = "text",
		tags = {"text","plant","forest","floor"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[65] = {
		name = "hand",
		unittype = "object",
		tags = {"abstract"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {3, 1},
	},
	[66] = {
		name = "text_hand",
		unittype = "text",
		tags = {"text","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 1},
		colour_active = {4, 2},
	},
	[67] = {
		name = "hedge",
		unittype = "object",
		tags = {"plant","obstacle"},
		tiling = 1,
		type = 0,
		layer = 14,
		colour = {5, 1},
	},
	[68] = {
		name = "text_hedge",
		unittype = "text",
		tags = {"text","plant","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 0},
		colour_active = {5, 1},
	},
	[69] = {
		name = "husk",
		unittype = "object",
		tags = {"plant","obstacle","autumn"},
		tiling = -1,
		type = 0,
		layer = 15,
		colour = {6, 1},
	},
	[70] = {
		name = "text_husk",
		unittype = "text",
		tags = {"text","plant","obstacle","autumn"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 1},
		colour_active = {6, 1},
	},
	[71] = {
		name = "ice",
		unittype = "object",
		tags = {"mountain","floor","common"},
		tiling = 1,
		type = 0,
		layer = 9,
		colour = {1, 2},
	},
	[72] = {
		name = "text_ice",
		unittype = "text",
		tags = {"text","mountain","floor","common"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 3},
	},
	[73] = {
		name = "jelly",
		unittype = "object",
		tags = {"water","animal","danger"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {1, 4},
	},
	[74] = {
		name = "text_jelly",
		unittype = "text",
		tags = {"text","water","animal","danger"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[75] = {
		name = "keke",
		unittype = "object",
		tags = {"common","animal"},
		tiling = 2,
		type = 0,
		layer = 18,
		colour = {2, 2},
	},
	[76] = {
		name = "text_keke",
		unittype = "text",
		tags = {"text","common","animal"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[77] = {
		name = "key",
		unittype = "object",
		tags = {"common","item"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {2, 4},
	},
	[78] = {
		name = "text_key",
		unittype = "text",
		tags = {"text","common","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[79] = {
		name = "ladder",
		unittype = "object",
		tags = {"item","machine"},
		tiling = -1,
		type = 0,
		layer = 10,
		colour = {2, 3},
	},
	[80] = {
		name = "text_ladder",
		unittype = "text",
		tags = {"text","item","machine"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 2},
		colour_active = {2, 3},
	},
	[81] = {
		name = "lava",
		sprite = "water",
		unittype = "object",
		tags = {"obstacle","cave","danger"},
		tiling = 1,
		type = 0,
		layer = 2,
		colour = {2, 3},
	},
	[82] = {
		name = "text_lava",
		unittype = "text",
		tags = {"text","obstacle","cave","danger"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 2},
		colour_active = {2, 3},
	},
	[83] = {
		name = "leaf",
		unittype = "object",
		tags = {"plant","autumn","decorative"},
		tiling = -1,
		type = 0,
		layer = 8,
		colour = {2, 4},
	},
	[84] = {
		name = "text_leaf",
		unittype = "text",
		tags = {"text","plant","autumn","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[85] = {
		name = "line",
		unittype = "object",
		tags = {"abstract","common"},
		tiling = 1,
		type = 0,
		layer = 21,
		colour = {0, 3},
	},
	[86] = {
		name = "text_line",
		unittype = "text",
		tags = {"text","abstract","common"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 2},
		colour_active = {0, 3},
	},
	[87] = {
		name = "love",
		unittype = "object",
		tags = {"common","abstract","decorative"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {4, 2},
	},
	[88] = {
		name = "text_love",
		unittype = "text",
		tags = {"text","common","abstract","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 1},
		colour_active = {4, 2},
	},
	[89] = {
		name = "me",
		unittype = "object",
		tags = {"common","animal"},
		tiling = 2,
		type = 0,
		layer = 18,
		colour = {3, 1},
	},
	[90] = {
		name = "text_me",
		unittype = "text",
		tags = {"text","common","animal"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 0},
		colour_active = {3, 1},
	},
	[91] = {
		name = "moon",
		unittype = "object",
		tags = {"sky","decorative"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {2, 4},
	},
	[92] = {
		name = "text_moon",
		unittype = "text",
		tags = {"text","sky","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[93] = {
		name = "orb",
		unittype = "object",
		tags = {"common","item"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {4, 1},
	},
	[94] = {
		name = "text_orb",
		unittype = "text",
		tags = {"text","common","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
	},
	[95] = {
		name = "pillar",
		unittype = "object",
		tags = {"ruins","obstacle"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {0, 1},
	},
	[96] = {
		name = "text_pillar",
		unittype = "text",
		tags = {"text","ruins","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 0},
		colour_active = {0, 1},
	},
	[97] = {
		name = "pipe",
		unittype = "object",
		tags = {"machine","obstacle"},
		tiling = 1,
		type = 0,
		layer = 14,
		colour = {1, 1},
	},
	[98] = {
		name = "text_pipe",
		unittype = "text",
		tags = {"text","machine","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 1},
		colour_active = {0, 1},
	},
	[99] = {
		name = "reed",
		unittype = "object",
		tags = {"forest","plant","decorative"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {6, 2},
	},
	[100] = {
		name = "text_reed",
		unittype = "text",
		tags = {"text","forest","plant","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 1},
		colour_active = {6, 2},
	},
	[101] = {
		name = "robot",
		unittype = "object",
		tags = {"machine"},
		tiling = 2,
		type = 0,
		layer = 17,
		colour = {0, 1},
	},
	[102] = {
		name = "text_robot",
		unittype = "text",
		tags = {"text","machine"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 0},
		colour_active = {0, 1},
	},
	[103] = {
		name = "rocket",
		unittype = "object",
		tags = {"machine","sky"},
		tiling = 0,
		type = 0,
		layer = 15,
		colour = {0, 1},
	},
	[104] = {
		name = "text_rocket",
		unittype = "text",
		tags = {"text","machine","sky"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 0},
		colour_active = {0, 1},
	},
	[105] = {
		name = "rock",
		unittype = "object",
		tags = {"common","item","cave"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {6, 2},
	},
	[106] = {
		name = "text_rock",
		unittype = "text",
		tags = {"text","common","item","cave"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 1},
	},
	[107] = {
		name = "rose",
		unittype = "object",
		tags = {"plant","decorative","forest"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {2, 2},
	},
	[108] = {
		name = "text_rose",
		unittype = "text",
		tags = {"text","plant","decorative","forest"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[109] = {
		name = "rubble",
		unittype = "object",
		tags = {"mountain","decorative","floor"},
		tiling = 1,
		type = 0,
		layer = 8,
		colour = {6, 1},
	},
	[110] = {
		name = "text_rubble",
		unittype = "text",
		tags = {"text","mountain","decorative","floor"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 1},
	},
	[111] = {
		name = "text_x",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[112] = {
		name = "shirt",
		unittype = "object",
		tags = {"item"},
		tiling = -1,
		type = 0,
		layer = 15,
		colour = {2, 1},
	},
	[113] = {
		name = "text_shirt",
		unittype = "text",
		tags = {"text","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 1},
		colour_active = {2, 1},
	},
	[114] = {
		name = "skull",
		unittype = "object",
		tags = {"common","danger"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {2, 1},
	},
	[115] = {
		name = "text_skull",
		unittype = "text",
		tags = {"text","common","danger"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 0},
		colour_active = {2, 1},
	},
	[116] = {
		name = "spike",
		unittype = "object",
		tags = {"mountain","decorative","danger"},
		tiling = -1,
		type = 0,
		layer = 10,
		colour = {1, 1},
	},
	[117] = {
		name = "text_spike",
		unittype = "text",
		tags = {"text","mountain","decorative","danger"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 1},
		colour_active = {0, 1},
	},
	[118] = {
		name = "star",
		unittype = "object",
		tags = {"sky","decorative","item"},
		tiling = -1,
		type = 0,
		layer = 16,
		colour = {2, 4},
	},
	[119] = {
		name = "text_star",
		unittype = "text",
		tags = {"text","sky","decorative","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[120] = {
		name = "statue",
		unittype = "object",
		tags = {"ruins","decorative"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {0, 1},
	},
	[121] = {
		name = "text_statue",
		unittype = "text",
		tags = {"text","ruins","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 2},
	},
	[122] = {
		name = "stump",
		unittype = "object",
		tags = {"ruins","forest","plant","decorative","obstacle"},
		tiling = -1,
		type = 0,
		layer = 12,
		colour = {6, 1},
	},
	[123] = {
		name = "text_stump",
		unittype = "text",
		tags = {"text","ruins","forest","plant","decorative","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 2},
	},
	[124] = {
		name = "sun",
		unittype = "object",
		tags = {"mountain","decorative","sky"},
		tiling = -1,
		type = 0,
		layer = 14,
		colour = {2, 4},
	},
	[125] = {
		name = "text_sun",
		unittype = "text",
		tags = {"text","mountain","decorative","sky"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 3},
		colour_active = {2, 4},
	},
	[126] = {
		name = "text_right",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[127] = {
		name = "text_up",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[128] = {
		name = "text_left",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[129] = {
		name = "text_down",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[130] = {
		name = "text_all",
		unittype = "text",
		unpaired = true,
		tags = {"text","text_special"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[131] = {
		name = "text_and",
		unittype = "text",
		tags = {"text","text_verb","common"},
		tiling = -1,
		type = 6,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[132] = {
		name = "text_best",
		unittype = "text",
		tags = {"text","text_quality","decorative"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 3},
		colour_active = {2, 4},
	},
	[133] = {
		name = "text_red",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[134] = {
		name = "text_blue",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {3, 2},
		colour_active = {3, 3},
	},
	[135] = {
		name = "text_green",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[136] = {
		name = "text_yellow",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[137] = {
		name = "text_purple",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {3, 0},
		colour_active = {3, 1},
	},
	[138] = {
		name = "text_pink",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
	},
	[139] = {
		name = "text_grey",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 1},
		colour_active = {0, 1},
	},
	[140] = {
		name = "text_black",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {0, 0},
		colour_active = {1, 1},
	},
	[141] = {
		name = "text_white",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[142] = {
		name = "text_brown",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 1},
		colour_active = {6, 1},
	},
	[143] = {
		name = "text_orange",
		unittype = "text",
		tags = {"text","text_quality","decorative","colour"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 2},
		colour_active = {2, 3},
	},
	[144] = {
		name = "text_bonus",
		unittype = "text",
		tags = {"text","common","text_quality","text_special"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
		advanced = true,
	},
	[145] = {
		name = "text_chill",
		unittype = "text",
		tags = {"text","text_quality","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {3, 2},
		colour_active = {3, 3},
	},
	[146] = {
		name = "text_cursor",
		unittype = "text",
		tags = {"text","text_special"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {2, 3},
		colour_active = {2, 4},
		special = true,
	},
	[147] = {
		name = "text_defeat",
		unittype = "text",
		tags = {"text","text_quality","danger"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 0},
		colour_active = {2, 1},
	},
	[148] = {
		name = "text_eat",
		unittype = "text",
		tags = {"text","text_verb"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[149] = {
		name = "text_empty",
		unittype = "text",
		tags = {"text","common","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[150] = {
		name = "text_end",
		unittype = "text",
		tags = {"text","text_quality","text_special"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[151] = {
		name = "text_facing",
		unittype = "text",
		tags = {"text","text_condition"},
		tiling = -1,
		type = 7,
		layer = 20,
		colour = {0, 2},
		colour_active = {0, 3},
		argextra = {"right","up","left","down"},
	},
	[152] = {
		name = "text_back",
		unittype = "text",
		tags = {"text","text_quality","abstract","text_special","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
		advanced = true,
		redacted = true,
	},
	[153] = {
		name = "text_fall",
		sprite = "text_falldown",
		unittype = "text",
		tags = {"text","text_quality","sky","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[154] = {
		name = "text_fallright",
		unittype = "text",
		tags = {"text","text_quality","sky","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[155] = {
		name = "text_fallup",
		unittype = "text",
		tags = {"text","text_quality","sky","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[156] = {
		name = "text_fallleft",
		unittype = "text",
		tags = {"text","text_quality","sky","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[157] = {
		name = "text_fear",
		unittype = "text",
		tags = {"text","text_verb","danger","movement"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[158] = {
		name = "text_float",
		unittype = "text",
		tags = {"text","text_quality","water"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 4},
	},
	[159] = {
		name = "text_follow",
		unittype = "text",
		tags = {"text","text_verb","movement"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {5, 0},
		colour_active = {5, 2},
	},
	[160] = {
		name = "text_group",
		unittype = "text",
		tags = {"text","common","text_special"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 2},
		colour_active = {3, 3},
		advanced = true,
	},
	[161] = {
		name = "text_has",
		unittype = "text",
		tags = {"text","text_verb","common"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[162] = {
		name = "text_hide",
		unittype = "text",
		tags = {"text","text_quality","text_special","abstract"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {3, 2},
		colour_active = {3, 3},
	},
	[163] = {
		name = "text_hot",
		unittype = "text",
		tags = {"text","text_quality","cave","danger"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 2},
		colour_active = {2, 3},
	},
	[164] = {
		name = "text_idle",
		unittype = "text",
		tags = {"text","text_condition","text_prefix"},
		tiling = -1,
		type = 3,
		layer = 20,
		colour = {2, 2},
		colour_active = {2, 3},
	},
	[165] = {
		name = "text_is",
		unittype = "text",
		tags = {"text","text_verb","common"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		argtype = {0, 2},
	},
	[166] = {
		name = "text_level",
		unittype = "text",
		tags = {"text","text_special","common"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
		advanced = true,
	},
	[167] = {
		name = "text_lonely",
		unittype = "text",
		tags = {"text","text_condition","text_prefix","mountain"},
		tiling = -1,
		type = 3,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[168] = {
		name = "text_often",
		unittype = "text",
		tags = {"text","text_condition","text_prefix","abstract","common"},
		tiling = -1,
		type = 3,
		layer = 20,
		colour = {5, 2},
		colour_active = {5, 3},
	},
	[169] = {
		name = "text_seldom",
		unittype = "text",
		tags = {"text","text_condition","text_prefix","abstract","common"},
		tiling = -1,
		type = 3,
		layer = 20,
		colour = {3, 2},
		colour_active = {3, 3},
	},
	[170] = {
		name = "text_make",
		unittype = "text",
		tags = {"text","text_verb","common"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[171] = {
		name = "text_melt",
		unittype = "text",
		tags = {"text","text_quality","cave","danger"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 3},
	},
	[172] = {
		name = "text_more",
		unittype = "text",
		tags = {"text","text_quality","abstract","common"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
	},
	[173] = {
		name = "text_move",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[174] = {
		name = "text_near",
		unittype = "text",
		tags = {"text","text_condition","common"},
		tiling = -1,
		type = 7,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[175] = {
		name = "text_not",
		unittype = "text",
		tags = {"text","text_special","common"},
		tiling = -1,
		type = 4,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[176] = {
		name = "text_on",
		unittype = "text",
		tags = {"text","text_condition","common"},
		tiling = -1,
		type = 7,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[177] = {
		name = "text_open",
		unittype = "text",
		tags = {"text","text_quality","common","obstacle"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[178] = {
		name = "text_you2",
		unittype = "text",
		tags = {"text","text_quality","text_special","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
		advanced = true,
	},
	[179] = {
		name = "text_play",
		unittype = "text",
		tags = {"text","text_verb","common"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
		argtype = {8},
		customobjects = {"a","b","c","d","e","f","g"},
		--redacted = true,
	},
	[180] = {
		name = "text_powered",
		unittype = "text",
		tags = {"text","text_condition","text_prefix","machine"},
		tiling = -1,
		type = 3,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[181] = {
		name = "text_power",
		unittype = "text",
		tags = {"text","text_quality","machine"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[182] = {
		name = "text_pull",
		unittype = "text",
		tags = {"text","text_quality","common","obstacle","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {6, 1},
		colour_active = {6, 2},
	},
	[183] = {
		name = "text_push",
		unittype = "text",
		tags = {"text","text_quality","common","obstacle","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {6, 0},
		colour_active = {6, 1},
	},
	[184] = {
		name = "text_sad",
		unittype = "text",
		tags = {"text","text_quality","decorative"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 1},
		colour_active = {3, 2},
	},
	[185] = {
		name = "text_safe",
		unittype = "text",
		tags = {"text","text_quality","common"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[186] = {
		name = "text_shift",
		unittype = "text",
		tags = {"text","text_quality","common","machine","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 3},
	},
	[187] = {
		name = "text_shut",
		unittype = "text",
		tags = {"text","text_quality","common","obstacle"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
	},
	[188] = {
		name = "text_sink",
		unittype = "text",
		tags = {"text","text_quality","common","obstacle","water","danger"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 3},
	},
	[189] = {
		name = "text_sleep",
		unittype = "text",
		tags = {"text","text_quality","sky","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 3},
		colour_active = {1, 4},
	},
	[190] = {
		name = "text_stop",
		unittype = "text",
		tags = {"text","text_quality","common","movement","obstacle"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 0},
		colour_active = {5, 1},
	},
	[191] = {
		name = "text_swap",
		unittype = "text",
		tags = {"text","text_quality","abstract","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {3, 0},
		colour_active = {3, 1},
		advanced = true,
	},
	[192] = {
		name = "text_tele",
		unittype = "text",
		tags = {"text","text_quality","abstract","machine","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 4},
	},
	[193] = {
		name = "text_text",
		unittype = "text",
		tags = {"text","text_special","common","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
		advanced = true,
	},
	[194] = {
		name = "tile",
		unittype = "object",
		tags = {"common","floor","decorative"},
		tiling = -1,
		type = 0,
		layer = 4,
		colour = {0, 0},
	},
	[195] = {
		name = "text_tile",
		unittype = "text",
		tags = {"text","common","floor","decorative"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 1},
		colour_active = {0, 1},
	},
	[196] = {
		name = "tree",
		unittype = "object",
		tags = {"forest","plant","obstacle"},
		tiling = -1,
		type = 0,
		layer = 15,
		colour = {5, 2},
	},
	[197] = {
		name = "text_tree",
		unittype = "text",
		tags = {"text","forest","plant","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 2},
	},
	[198] = {
		name = "ufo",
		unittype = "object",
		tags = {"sky","machine"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {4, 2},
	},
	[199] = {
		name = "text_ufo",
		unittype = "text",
		tags = {"text","sky","machine"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
	},
	[200] = {
		name = "wall",
		unittype = "object",
		tags = {"common","obstacle"},
		tiling = 1,
		type = 0,
		layer = 14,
		colour = {1, 1},
	},
	[201] = {
		name = "text_wall",
		unittype = "text",
		tags = {"text","common","obstacle"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 1},
		colour_active = {0, 1},
	},
	[202] = {
		name = "water",
		unittype = "object",
		tags = {"water","obstacle","danger"},
		tiling = 1,
		type = 0,
		layer = 2,
		colour = {1, 3},
	},
	[203] = {
		name = "text_water",
		unittype = "text",
		tags = {"text","water","obstacle","danger"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 3},
	},
	[204] = {
		name = "text_weak",
		unittype = "text",
		tags = {"text","text_quality","danger"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 1},
		colour_active = {1, 2},
	},
	[205] = {
		name = "text_win",
		unittype = "text",
		tags = {"text","text_quality","common"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {6, 1},
		colour_active = {2, 4},
	},
	[206] = {
		name = "text_without",
		unittype = "text",
		tags = {"text","text_condition","common"},
		tiling = -1,
		type = 7,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[207] = {
		name = "text_wonder",
		unittype = "text",
		tags = {"text","text_quality","decorative"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
	[208] = {
		name = "text_word",
		unittype = "text",
		tags = {"text","text_quality","text_special"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {0, 2},
		colour_active = {0, 3},
		advanced = true,
	},
	[209] = {
		name = "text_you",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
	},
	[210] = {
		name = "tinyhusk",
		unittype = "object",
		tags = {"plant","autumn","decorative"},
		tiling = -1,
		type = 0,
		layer = 9,
		colour = {6, 1},
	},
	[211] = {
		name = "tinytree",
		unittype = "object",
		tags = {"forest","plant","decorative"},
		tiling = -1,
		type = 0,
		layer = 9,
		colour = {5, 2},
	},
	[212] = {
		name = "text_a",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[213] = {
		name = "text_b",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[214] = {
		name = "text_c",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[215] = {
		name = "text_d",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[216] = {
		name = "text_e",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[217] = {
		name = "text_f",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[218] = {
		name = "text_g",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[219] = {
		name = "text_h",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[220] = {
		name = "text_i",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[221] = {
		name = "text_l",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[222] = {
		name = "text_m",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[223] = {
		name = "text_n",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[224] = {
		name = "text_o",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[225] = {
		name = "text_r",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[226] = {
		name = "text_s",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[227] = {
		name = "text_t",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[228] = {
		name = "text_u",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[229] = {
		name = "text_v",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[230] = {
		name = "text_j",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[231] = {
		name = "text_k",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[232] = {
		name = "text_p",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[233] = {
		name = "text_q",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[234] = {
		name = "text_y",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[235] = {
		name = "text_z",
		unittype = "text",
		tags = {"text","text_letter"},
		tiling = -1,
		type = 5,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		advanced = true,
	},
	[236] = {
		name = "text_broken",
		unittype = "text",
		tags = {"text","text_quality","abstract"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
		advanced = true,
	},
	[237] = {
		name = "text_nudgeright",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
		advanced = true,
	},
	[238] = {
		name = "text_nudgeup",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
		advanced = true,
	},
	[239] = {
		name = "text_nudgeleft",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
		advanced = true,
	},
	[240] = {
		name = "text_nudgedown",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
		advanced = true,
	},
	[241] = {
		name = "text_turn",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 4},
	},
	[242] = {
		name = "text_deturn",
		unittype = "text",
		tags = {"text","text_quality","common","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {1, 2},
		colour_active = {1, 4},
	},
	[243] = {
		name = "text_done",
		unittype = "text",
		tags = {"text","text_quality","text_special"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
		special = true,
	},
	[244] = {
		name = "text_mimic",
		unittype = "text",
		tags = {"text","text_verb","abstract"},
		tiling = -1,
		type = 1,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
		advanced = true,
	},
	[245] = {
		name = "sign",
		unittype = "object",
		tags = {"common","item"},
		tiling = -1,
		type = 0,
		layer = 12,
		colour = {6, 1},
	},
	[246] = {
		name = "text_sign",
		unittype = "text",
		tags = {"text","common","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {6, 1},
		colour_active = {6, 2},
	},
	[247] = {
		name = "text_still",
		unittype = "text",
		tags = {"text","text_quality","abstract","movement"},
		tiling = -1,
		type = 2,
		layer = 20,
		colour = {2, 1},
		colour_active = {2, 2},
		advanced = true,
	},
	[248] = {
		name = "circle",
		unittype = "object",
		tags = {"item","abstract"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {5, 3},
	},
	[249] = {
		name = "text_circle",
		unittype = "text",
		tags = {"text","item","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {5, 1},
		colour_active = {5, 3},
	},
	[250] = {
		name = "square",
		unittype = "object",
		tags = {"item","abstract"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {4, 1},
	},
	[251] = {
		name = "text_square",
		unittype = "text",
		tags = {"text","item","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 0},
		colour_active = {4, 1},
	},
	[252] = {
		name = "triangle",
		unittype = "object",
		tags = {"item","abstract"},
		tiling = -1,
		type = 0,
		layer = 17,
		colour = {3, 2},
	},
	[253] = {
		name = "text_triangle",
		unittype = "text",
		tags = {"text","item","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 2},
		colour_active = {3, 3},
	},
	[254] = {
		name = "crystal",
		unittype = "object",
		tags = {"cave","obstacle","item"},
		tiling = -1,
		type = 0,
		layer = 12,
		colour = {4, 2},
	},
	[255] = {
		name = "text_crystal",
		unittype = "text",
		tags = {"text","cave","obstacle","item"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {4, 1},
		colour_active = {4, 2},
	},
	[256] = {
		name = "foot",
		unittype = "object",
		tags = {"abstract"},
		tiling = 0,
		type = 0,
		layer = 17,
		colour = {3, 1},
	},
	[257] = {
		name = "text_foot",
		unittype = "text",
		tags = {"text","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 1},
		colour_active = {4, 2},
	},
	[258] = {
		name = "eye",
		unittype = "object",
		tags = {"abstract"},
		tiling = 2,
		type = 0,
		layer = 19,
		colour = {3, 1},
	},
	[259] = {
		name = "text_eye",
		unittype = "text",
		tags = {"text","abstract"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {3, 1},
		colour_active = {4, 2},
	},
	[260] = {
		name = "worm",
		unittype = "object",
		tags = {"forest","animal"},
		tiling = 2,
		type = 0,
		layer = 19,
		colour = {0, 3},
	},
	[261] = {
		name = "text_worm",
		unittype = "text",
		tags = {"text","forest","animal"},
		tiling = -1,
		type = 0,
		layer = 20,
		colour = {0, 1},
		colour_active = {0, 3},
	},
}