[tiles]
object001_layer=20
object119_type=3
object119_name=text_idle
object119_image=text_idle
object078_name=text_turn
changed=object000,object119,object078,object001,

[general]
selectorY=-1
unlockcount=0
selectorX=-1
leveltype=0
specials=0
paths=0
levels=1
palette=default.png
customparent=
paletteroot=1
name=bug catcher

[levels]
0name=
0file=bug catcher
0Z=0
0colour=0,3
0clearcolour=0,2
0state=2
0X=18
0Y=13
0style=-2
0number=0
0dir=0

