[tiles]
object099_image=text_hawke
object099_colour=1,2
object099_activecolour=1,4
object068_image=hawke
object099_root=0
object068_colour=0,3
object099_name=text_hawke
object068_name=hawke
object068_root=0
changed=object068,object099,

[general]
unlockcount=0
specials=0
selectorY=-1
paths=0
palette=default.png
paletteroot=1
name=collinearity
music=baba
selectorX=-1
leveltype=0
levels=0
customparent=

