[tiles]
object063_name=text_bolt
object063_root=0
object091_image=text_orb
object051_name=bolt
object051_root=0
object063_image=text_bolt
object100_image=line
object100_tiling=-1
object051_image=bolt
changed=object100,object051,object091,object063,

[general]
unlockcount=0
subtitle=this level inspired the word 'idle'!
specials=0
selectorY=-1
paths=0
particles=soot
palette=space.png
paletteroot=1
name=grappling hook
selectorX=-1
leveltype=0
levels=0
customparent=

