[tiles]
object107_image=text_wug
object041_root=0
object041_image=bolt
object041_tiling=0
object098_root=0
object107_root=0
object098_name=wug
object098_image=wug
object098_tiling=0
object107_name=text_wug
changed=object098,object041,object107,

[general]
selectorY=-1
unlockcount=0
selectorX=-1
leveltype=0
specials=0
paths=0
levels=0
palette=factory.png
customparent=
paletteroot=1
name=understocked
music=factory

