[tiles]
object063_name=text_bolt
object063_root=0
object091_image=text_orb
object051_name=bolt
object051_root=0
object100_activecolour=-1,-1
object100_tiling=-1
object063_image=text_bolt
object100_image=line
object100_colour=6,1
object051_image=bolt
changed=object100,object051,object091,object063,

[general]
name=bouncy house
paletteroot=1
customparent=
palette=space.png
levels=0
paths=0
specials=0
leveltype=0
selectorX=-1
unlockcount=0
selectorY=-1
particles=soot

